link_saver/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('users.urls', namespace='users')),
    url(r'', include('links.urls', namespace='links')),
]

links/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^$', views.links_index, name='links_index'),
    url(r'^add_category/', views.add_category, name='add_category'),
    url(r'^add_link/', views.add_link, name='add_link'),
    url(r'^(?P<link_id>\d+)/update_link/', views.update_link, name='update_link'),
    url(r'^(?P<link_id>\d+)/delete_link/', views.delete_link, name='delete_link'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    url(r'^login/', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^register/register_me_pls/', views.register, name='register'),
]

links/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = 'categories'


    def __str__(self):
        return self.name


class Link(models.Model):
    id = models.AutoField(primary_key=True)
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=200)
    starred = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now_add=True)
    reference = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = 'links'
        ordering = ('-starred', '-date_added')

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

links/forms.py
from django import forms

from links.models import Category, Link

class AddCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']
        labels = {'name': 'Category name'}


class AddLinkForm(forms.ModelForm):
    class Meta:
        model = Link
        fields = ['title', 'category', 'reference']

links/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from datetime import date

from links.models import Category, Link
from links.forms import AddCategoryForm, AddLinkForm

import math

# Create your views here.

@login_required
def index(request):
    return render(request, 'links/index.html')

@login_required
def links_index(request):
    """ show link, return categories """
    links = Link.objects.all()

    links_count = len(links)
    links_per_page = 7

    categories = Category.objects.all()
    paginator = Paginator(links, links_per_page)
    page = request.GET.get('page')

    try:
        links = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        links = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        links = paginator.page(paginator.num_pages)

    category_form = add_category(request)
    link_form = add_link(request)

    today = date.today()

    pages = math.ceil(links_count / links_per_page)

    context = {'links': links, 'categories': categories, 'category_form': category_form, 'link_form': link_form, 'links_count': links_count,
        'today': today, 'pages': pages}
    return render(request, 'links/index.html', context)


@login_required
def add_category(request):
    if request.method != 'POST':
        form = AddCategoryForm()
    else:
        form = AddCategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('links:links_index'))
    
    return form


@login_required
def add_link(request):
    if request.method != 'POST':
        form = AddLinkForm()
    else:
        form = AddLinkForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('links:links_index'))
        
    return form


@login_required
def update_link(request, link_id):
    link = Link.objects.get(id=link_id)

    if link.starred == False:
        link.starred = True
        link.save()
    else:
        link.starred = False
        link.save()

    return HttpResponseRedirect(reverse('links:links_index'))


@login_required
def delete_link(request, link_id):
    link = Link.objects.get(id=link_id)
    link.delete()
    return HttpResponseRedirect(reverse('links:links_index'))

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('links:links_index'))

    context = {'form': form}
    return render(request, 'register.html', context)

links/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>link_saver - {% block title %}{% endblock %}</title>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">      
    <style>
        #star {color: gold;}
        .left-my {margin-left: 10px;}
        .right-my {margin-right: 10px;}
        .my-pagin {color: white;}
    </style>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <nav>
            <div class="nav-wrapper teal">
                <a href="#" class="brand-logo center">link_Saver {% block brand %}{% endblock %}</a>
                    {% if user.is_authenticated %}
                        <span class="left left-my">
                            <ul id="nav-mobile" class="left hide-on-med-and-down">
                                <li>Logged as: {{ user.username }}</li>
                                <li><a class="waves-effect waves-light btn" href="{% url 'users:logout' %}">Logout <i class="material-icons right">exit_to_app</i></a></li>
                            </ul>
                        </span>
                    {% endif %}
                    <span class="right right-my">{% block counter %}{% endblock %}</span>

            </div>
        </nav>
        <div class="container">

            {% comment %} {% for message in get_flashed_messages() %}
                <div class="flash"></div>
            {% endfor %} {% endcomment %}


            {% block content %}
        
            {% endblock %}


        </div>        
        <!-- Compiled and minified JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <!-- <script src="app/assets/js/jquery.js"></script>

        <script src="app/app.js"></script>

        <script src="app/links/links.js"></script>
        <script src="app/links/read-links.js"></script>
        <script src="app/links/delete-link.js"></script>
        <script src="app/links/create-link.js"></script>
        <script src="app/links/update-link.js"></script>

        <script src="app/categories/create-category.js"></script> -->

        <script>
            document.addEventListener('DOMContentLoaded', function() {
                var elems = document.querySelectorAll('select');
                var instances = M.FormSelect.init(elems);
            });
        </script>
        <script>

            document.addEventListener('DOMContentLoaded', function() {
                var elems = document.querySelectorAll('.modal');
                var instances = M.Modal.init(elems);
            });

        </script>
        </body>
    </html>

links/templates/links/index.html
{% extends 'base.html' %}

{% block brand %}
    - link_adder
{% endblock %}

{% block counter %}
    today is: {{ today|date:'Y-m-d'}} | there are: <b>{{ links_count }}</b> links on <b>{{ pages }}</b> {% if pages == 1 %}page{% else %}pages{% endif %}
{% endblock %}

{% block content %}
    <br />    
    {% comment %} {{ link_form.non_field_errors }} {% endcomment %}
    <form class="col s12" action="{% url 'links:add_link' %}" method="post" id="add-link-form">
        {% csrf_token %}
        <div class="row">
            <div class="input-field col s3">
                {{ link_form.title }}
                <label for="{{form.subject.title}}">Title</label>
            </div>
        

            <div class="input-field col s3" required>
                {{ link_form.category }}
                <label for="{{form.subject.category}}" >Category</label>
            </div>

            <div class="input-field col s6">
                {{ link_form.reference }}
                <label for="{{form.subject.reference}}">Reference</label>
            </div>
        </div>

        <p>
            <button class="waves-effect waves-light btn right" type="submit">Add link</button>
            <button class="waves-effect waves-light btn left modal-trigger" data-target="modal1">Add new category</button>
        </p>
    </form>
    <br /><br /><br />
    <hr />

    <div id="links">
        <table class="responsive-table">
            <thead>
                <tr>
                    <th>starred</th>
                    <th>Title</th>
                    <th>Category</th>
                    <th>Date added</th>
                    <th>Refference</th>
                    <th>Delete</th>
                </tr>
            </thead>
            {% for link in links %}
                <tr>
                    <td>
                        {% if link.starred %}
                            <a href="{% url 'links:update_link' link.id %}"><i class="small material-icons waves-effect waves-light" id="star" data-id="{{ link.id }}">star</i></a>
                        {% else %}
                            <a href="{% url 'links:update_link' link.id %}"><i class="small material-icons waves-effect waves-light" id="star" data-id="{{ link.id }}">star_border</i></a>
                        {% endif %}
                    </td>
                    <td>{{ link.title }}</td>
                    <td>{{ link.category }}</td>
                    <td>{{ link.date_added|date:'Y-m-d H:i' }}</td>
                    <td><a href="{{ link.reference }}" class="waves-effect waves-light btn" target="_blank">GO <i class="material-icons right">send</i></a></td>
                    <!--<td><a class="modal-trigger" data-target="modal2" id="delete" title="delete" href="#" data-id="" ><i class="small material-icons">delete_forever</i></a></td>-->
                    <td><a href="{% url 'links:delete_link' link.id %}" onclick="return confirm('Are you sure?');"><i class="small material-icons">delete_forever</i></a></td>
                </tr>
            {% endfor %}
            {% comment %} {% empty %}
            <div>
                Brak wpisoów
            </div> {% endcomment %}

            <tbody>
            </tbody>
        </table>


        <ul class="pagination">
            {% if links.has_previous %}
                <li class="waves-effect"><a href="?page={{ links.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
            {% else %}
                <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
            {% endif %}
            {% if links.has_next %}
                <li class="waves-effect"><a href="?page={{ links.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
            {% else %}
                <li class="disabled"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
            {% endif %}
        </ul>


    </div>


    <!-- Modal Structure -->
    <div id="modal1" class="modal">
        <div class="modal-content">
            <h4>Adding category</h4>
            <form class="col s12" method="post" id="add-category-form" action="{% url 'links:add_category' %}">
                <div class="row">
                    <div class="input-field col s3">
                        {% comment %} <input name="name" id="name" type="text" class="validate" required> {% endcomment %}
                        {% csrf_token %}
                        {{ category_form }}
                        <label for="name">Category name</label>
                    </div>
                </div>
                <p>
                    <button class="waves-effect waves-light btn left" type="submit">Add category </button>
                </p>
            </form>
        </div>
        <div class="modal-footer">
            <a href="#" id="btn-cancel" class="modal-close waves-effect waves-green btn-flat">Cancel</a>
        </div>
        </div>
    </div>
{% endblock %}

users/templates/login.html
{% extends 'base.html' %}

{% block title %}login{% endblock %}

{% block brand %} - login{% endblock %}
 
{% block content %}
    <div class="section">
        <div class="row">
            {% if form.errors %}
                <p>Wrong username or password</p>
            {% endif %}

            <form method="post" class="col s12" action="{% url 'users:login' %}">
                {% csrf_token %}
                <div class="row">
                    <div class="input-field col s6">
                        {% comment %} <input type="text" name="username" id="username-field" class="validate" required> {% endcomment %}
                        {{ form.username }}
                        <label for="username-field">Username</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                        {{ form.password }}
                        {% comment %} <input type="password" name="password" id="password-field" class="validate" required> {% endcomment %}
                        <label for="password-field">Password</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                        <button class="btn waves-effect waves-light" type="submit" name="login-btn">Proceed
                            <i class="material-icons right">send</i>
                        </button>
                        <input type="hidden" name="next" value="{% url 'links:links_index' %}">
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

users/templates/register.html
{% extends 'base.html' %}

{% block title %}register{% endblock %}

{% block brand %} - register{% endblock %}

{% block content %}
    <div class="section">
        <div class="row">

            {% if form.errors %}
                <p>Something wrong</p>
            {% endif %}
            <form method="post" class="col s12" action="{% url 'users:register' %}">
                {% csrf_token %}
                <div class="row">
                    <div class="input-field col s6">
                        {{ form.username }}
                        <label for="username-field">Username <span style="color:red">*</span></label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                        {{ form.password1 }}
                        <label for="password-field">Password <span style="color:red">*</span></label>
                        <small>
                            <ul>
                                <li>at least 8 characters</li>
                                <li>not only numbers</li>
                            </ul>
                        </small>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                        {{ form.password2 }}
                        <label for="password-field">Repeat password <span style="color:red">*</span></label>
                    </div>
                </div>
                
                {% comment %} {{ form.as_p }} {% endcomment %}
                <div class="row">
                    <div class="input-field col s6">
                        <button class="btn waves-effect waves-light" type="submit" name="login-btn">Proceed
                            <i class="material-icons right">send</i>
                        </button>
                        <input type="hidden" name="next" value="{% url 'links:links_index' %}">
                    </div>
                </div>
                
            </form>
     
        </div>
            <div class="row">
                <div class="col s6">
                    <a href="{% url 'users:login' %}">login</a>
                </div>
            </div>
    </div>
{% endblock %}